Algoritmo "Variáveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleison Melo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Aguilar
// Data atual  : 25/08/2020
Var
// Seção de Declarações das variáveis
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    nota<- 100
    escreva("Resultado", nota)

Fimalgoritmo